version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      python: 3.8
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ....
      - ls -la
      #Lambda deploy reference
      #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
      #Build spec reference
      #https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
      # Package SAM template
      - sam build
      - sam deploy 
        --no-confirm-changeset 
        --no-fail-on-empty-changeset 
        --stack-name $PROJECT_NAME
        --resolve-s3 
        --capabilities CAPABILITY_NAMED_IAM
        # --parameter-overrides pVersion=2 pState=$PROJECT_NAME


      # - sam package --template-file template.yml --s3-bucket sam-matching-tool-artifacts --output-template-file packaged.yaml
      # - echo ls after package
      # - ls -la
      # Deploy packaged SAM template
      # - sam deploy --template-file packaged.yaml --stack-name matchingTool --capabilities CAPABILITY_IAM
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths