version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tfqvcgvrymlx"
s3_prefix = "s3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "pBranch=\"main\" pProjectName=\"s3\" pOauthToken=\"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\" pRepoUrl=\"https://github.com/perinei/s3-upload\" pBucketPrefix=\"files\" pTargetBucketPrefix=\"users\" pTargetBucketName=\"perinei-s3-upload\""
